FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        Cython \
        libxml2-devel \
        libxslt-devel \
        python-beautifulsoup4 \
        python-cssselect \
        python-devel \
        python-html5lib \
        python-setuptools \
        python36-Cython \
        python36-devel \
        python36-setuptools \
    && yum clean all && rm -rf /var/cache/yum
